version: '3.9'
services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"  
    volumes:
      - ./migrate/:/docker-entrypoint-initdb.d/