version: 2.1

jobs:
  test-gotestsum:
    docker:
      - image: golang:latest
    working_directory: ~/project
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Test with gotestsum
          command: |
            go install gotest.tools/gotestsum@latest
            gotestsum --format json || (gotestsum --format json > test_results.json && exit 1)
          when: always
      - store_artifacts:
          path: test_results.json
          destination: gotestsum
  
  test-golangci-lint:
    docker:
      - image: golang:latest
    working_directory: ~/project
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Lint with golangci-lint
          command: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            golangci-lint run --out-format=json > golangci-lint-results.json || true
          when: always
      - store_artifacts:
          path: golangci-lint-results.json
          destination: golangci-lint
         
  build:
    docker:
      - image: golang:latest
    working_directory: ~/project
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Build
          command: go build -o myapp
      - run:
          name: Build and tag Docker image
          command: |
            if [[ "$CIRCLE_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              docker build -t grpc-postgresql:$CIRCLE_SHA1 -f /build/Dockerfile .
            else
              echo "Skipping Docker image build and tag because this is not a semver tag or a merge to main/master."
            fi
                        
  deploy:
    docker:
      - image: grpc-postgresql:$CIRCLE_SHA1
    steps:
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push grpc-postgresql:$CIRCLE_SHA1


workflows:
  build-and-deploy:
    jobs:
      - test-gotestsum
      - test-golangci-lint:
          requires:
            - test-gotestsum
      - build:
          requires:
            - test-gotestsum
            - test-golangci-lint
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
