apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  labels:
    app: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: nginx:1.14.2 # TODO
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service # Sets service name
  labels:
    app: shop # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 80 # Sets port to run the postgres application
  selector:
    app: shop